# config.yaml

# Data configuration
data:
  path: "data/po_list_data.json"
  output_dir: "output"
  generate_data: true  # Set to false to use existing data
  data_name: "po_list_data"  # Name of the data file (without extension)

# MCMC run configuration
mcmc:
  num_iterations: 200000    # Total number of MCMC iterations
  K: 3                     # Latent dimension (number of columns in U)
  update_probabilities:
    rho: 0.1              # Proportion of iterations to update rho
    noise: 0.2            # Proportion of iterations to update noise parameter(s)
    U: 0.3                # Proportion of iterations to update the latent variable U
    beta: 0.2
    K: 0.2

# Configuration for updating œÅ
rho:
  dr: 0.8                 # Multiplicative step size for rho update

beta:
  drbeta: 0.8                 # Multiplicative step size for rho update

random_seed: 42
# Visualization settings
visualization:
  burn_in: 10              # Increased burn-in period
  output_filename: "mcmc_inferred_result.pdf"
  output_filepath: "output"

  
#############################Below are the configurations for data generation####################################
generation:
  n: 10                    # Number of nodes/items in the partial order
  N: 100                   # Number of total orders to sample from the partial order
  K: 3                     # Number of dimensions for latent positions
  p: 2                     # Number of covariates


# Covariates configuration
covariates:
  p: 2
  beta_true: [0.5, -0.3]

# Configuration for noise parameter updates
noise:
  noise_option: "queue_jump"   # Options: "mallows_noise" or "queue_jump"
  sigma_mallow: 0.5           # Proposal standard deviation for Mallows theta update

# Prior parameters
prior:
  rho_prior: 0.16667         # Prior probability of rho
  noise_beta_prior: 9        # Beta prior parameter for noise (if applicable)
  mallow_ua: 10              # Exponential rate parameter for Mallows theta
  sigma_u: 0.5               # Prior standard deviation for U shift
  K_prior: 3                 # Poisson distribution with truncated lambda distribution
  sigma_beta: 0.5               # Prior standard deviation for U shift